# -*- coding: utf-8 -*-
"""noshow 전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xy7WTUEuSPsE3EteV-crQ51TSR-INEKM
"""

#!/usr/bin/env python
# coding: utf-8
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import time

##### 데이터 전처리 시작 #####
# path = './_data/'
# datasets = pd.read_csv(path + 'medical_noshow.csv')
datasets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/_data/medical_noshow.csv')

print('columns : \n',datasets.columns)
print('head : \n',datasets.head(7))

x = datasets[['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received']]
y = datasets[['No-show']]
print(x.shape, y.shape)

print(x.info())  # info() 컬럼명, null값, data타입 확인

print(x.describe())

# 결과에 영향을 주지 않는 값 삭제
x = x.drop(['PatientId', 'AppointmentID'], axis=1)

print(x.shape)

x = x.fillna(np.NaN)    

# 문자를 숫자로 변경
from sklearn.preprocessing import LabelEncoder
ob_col = list(x.dtypes[x.dtypes=='object'].index)    # 오브젝트 컬럼 리스트 추출
print(ob_col)
for col in ob_col:
    x[col] = LabelEncoder().fit_transform(x[col].values)
y = LabelEncoder().fit_transform(y.values)
# no = 0 , yes = 1

x = x.fillna(np.NaN)

print('columns : \n',x.columns)
print('head : \n',x.head(7))
print('y : ',y[0:8])

###상관계수 히트맵###
import matplotlib.pyplot as plt
import seaborn as sns

# pip install seaborn
sns.set(font_scale = 1.2)
sns.set(rc = {'figure.figsize':(16, 10)})   # 히트맵 데이터 맵 말고 히트맵 그림의 크기
sns.heatmap(data = x.corr(), #상관관계
            square = True,
            annot = True,
            cbar = True,
           )

##### 전처리 완료 #####

x = datasets[['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received','No-show']]
y = datasets[['No-show']]
print(x.shape, y.shape)

# print(x.info())  # info() 컬럼명, null값, data타입 확인

# print(x.describe())

# 결과에 영향을 주지 않는 값 삭제
x = x.drop(['PatientId', 'AppointmentID'], axis=1)

# print(x.shape)

x = x.fillna(np.NaN)    

# 문자를 숫자로 변경
from sklearn.preprocessing import LabelEncoder
ob_col = list(x.dtypes[x.dtypes=='object'].index)    # 오브젝트 컬럼 리스트 추출
# print(ob_col)
for col in ob_col:
    x[col] = LabelEncoder().fit_transform(x[col].values)
y = LabelEncoder().fit_transform(y.values)
# no = 0 , yes = 1

x = x.fillna(np.NaN)

# print('columns : \n',x.columns)
# print('head : \n',x.head(7))
# print('y : ',y[0:8])

###상관계수 히트맵###
import matplotlib.pyplot as plt
import seaborn as sns

# pip install seaborn
sns.set(font_scale = 1.2)
sns.set(rc = {'figure.figsize':(16, 10)})   # 히트맵 데이터 맵 말고 히트맵 그림의 크기
sns.heatmap(data = x.corr(), #상관관계
            square = True,
            annot = True,
            cbar = True,
           )

##### 전처리 완료 #####